version: '2.2'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./front
    networks:
      - dev

networks:
  dev:
    driver: bridge
